### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by acasar** [LaravelCollective/remote#16]
I have a deploy script that runs ``composer install`` remotely. But it seems that if takes longer than 10 seconds it gets aborted by force. Is there any way to set a longer timeout for the connection?

Thanks!

**Comment by ikari7789** [comment]
Not sure if this is the best way to implement it, but this pull request will let you set a timeout.

**Comment by acasar** [comment]
@ikari7789 Thanks for this. I'll try it today and report back.

**Comment by ikari7789** [comment]
The tests for this package are lacking to say the least, so I'm unsure how the change would affect the overall usage. There's no direct input checking that the timeout is a valid integer or not.

**Comment by acasar** [comment]
I tried it and without changing anything else, I get the following error:

```
local.ERROR: exception 'ErrorException' with message 'Undefined index: timeout' in /var/www/vendor/laravelcollective/remote/src/RemoteManager.php:108
```

There should probably be some sort of isset check for timeout config? So that we don't break the anything?

**Comment by ikari7789** [comment]
I added the variable checking from your pull request, along with checking for the two other config variables, to my own pull request.

**Comment by HyperCommNet** [comment]
I am still having a issue

```
ErrorException in RemoteManager.php line 96:
Undefined index: timeout
```

**Comment by HyperCommNet** [comment]
And When i add timeout to the remote config
```
ErrorException in Connection.php line 64:
Argument 5 passed to Collective\Remote\Connection::__construct() must be an instance of Collective\Remote\GatewayInterface, integer given, called in /home/adonis/admin/vendor/laravelcollective/remote/src/RemoteManager.php on line 98 and defined
```
