### ISSUE TITLE
Remote Timeout Issue

### ISSUE THREAD

**Issue by HyperCommNet** [LaravelCollective/remote#20]
I am still having a issue
```
ErrorException in RemoteManager.php line 96:
Undefined index: timeout
```
And When i add timeout to the remote config
```
ErrorException in Connection.php line 64:
Argument 5 passed to Collective\Remote\Connection::__construct() must be an instance of Collective\Remote\GatewayInterface, integer given, called in /home/adonis/admin/vendor/laravelcollective/remote/src/RemoteManager.php on line 98 and defined
```

#16

**Comment by acasar** [comment]
The latest PR was not merged correctly. I prepared a fix: https://github.com/LaravelCollective/remote/pull/21

I hope it gets merged quickly.

**Comment by HyperCommNet** [comment]
Yea it broke my instance i had to revert back to 5.1.4 till it gets fixed.

**Comment by ikari7789** [comment]
I'm moreso wondering why the pull request wasn't just merged and instead cherry picked.
