### ISSUE TITLE
5.2 tag does not work with Laravel 5.2

### ISSUE THREAD

**Issue by ikari7789** [LaravelCollective/remote#23]
Please be aware that merely updating the composer packages to 5.2 does not allow this to work with Laravel 5.2.

There was deprecated code being used that was also removed from Laravel in 5.2. This was already addressed in PR #22.

**Comment by adamgoose** [comment]
Yeah, my bad... The SP is deferred, so I missed it in my testing. :P Sorry about that! Tagged v5.2.1.

**Comment by ikari7789** [comment]
No worries there. My only question is why ignore the pull request that was already made?

**Comment by adamgoose** [comment]
Sorry about that... I appreciate your efforts. I just had to go through all of our repositories and get them all set up for 5.2 releases. I wasn't even looking at PRs, and had forgotten that you had made one. :/

**Comment by adamgoose** [comment]
https://twitter.com/LaraCollective/status/679580192554156032

**Comment by ikari7789** [comment]
Completely understood. Thanks for the explanation!
