### ISSUE TITLE
How to use Collective/remote in laravel controller by SSH::define and SSH::task

### ISSUE THREAD

**Issue by wenzhu191** [LaravelCollective/remote#29]
HI,It is good tool for laravel framework
but,when I use in controller it not work !

first I define a task by method SSH::define then called SHH::task method to run the task It not work
by debugger I found tasks[$task] which is the property of Connect is empty.
Is that where I was wrong ? Look forward to your reply,thanks
by leechao

**Comment by avivronen** [comment]
Same problem here. :+1:

**Comment by OmarSabry** [comment]
it's very simple, just add your server credentials to app/config/remote.php file.
then make a controller and create public function, and here is the trick: just put \ before SSH::run();
like:

\SSH::run();
 
![snap 2016-10-09 at 11 24 09](https://cloud.githubusercontent.com/assets/7590947/19219415/33722948-8e13-11e6-93dc-e5afcccca7ce.png)

**Comment by mlantz** [comment]
Looked into this and found an issue - now you'll be able to chain the define with the tasks so it will look like: `SSH::define()->task()`.
