### ISSUE TITLE
Tail Command Doesn't Support "daily" log style

### ISSUE THREAD

**Issue by adamgoose** [LaravelCollective/remote#3]
Currently, the `php artisan tail` command only supports Laravel Applications with a "single" log setting. Other settings, namely "daily", will report that the log file cannot be found. We must determine a more reasonable default based on the application's log setting.

**Comment by RobinMalfait** [comment]
I think this belongs to laravel artisan stuff itself and not directly to the remote component?

**Comment by adamgoose** [comment]
Well it is, because the tail command is a part of the Remote Component, and has been removed from the core.

**Comment by RobinMalfait** [comment]
Oh didn't know that! `php artisan tail` should be a part of the core / logging stuff imho.

**Comment by tshafer** [comment]
Updated here. https://github.com/LaravelCollective/remote/pull/4
