### ISSUE TITLE
How to handle empty line / "Enter press"?

### ISSUE THREAD

**Issue by avivronen** [LaravelCollective/remote#30]
Hi,
Lets say mysql root password is empty after first install.

When running  mysql -u root -p command I need to put "empty" password - eg "\n",
but the library add '&&' at protected function formatCommands($commands).

How should we fake "enter" press?

Thanks

**Comment by adamgoose** [comment]
Try -p "" (with two double quotes). You cannot simulate a return.

**Comment by avivronen** [comment]
No Luck :-(

**Comment by adamgoose** [comment]
Sorry m8. You can't emulate a "return" signal.
