### ISSUE TITLE
"Unable to connect to remote server." No other feedback

### ISSUE THREAD

**Issue by DeanWard** [LaravelCollective/remote#33]
Getting error "Unable to connect to remote server." without any other feedback so I'm not really sure where to look to fix the problem?

Using 5.3 (laravel and remote).

Tried connecting using both key and password. The log file doesn't contain any more information about the error. I don't know if it's failing to contact the host, or if the host is rejecting credentials, or something else...

**Comment by jhoff** [comment]
Hey @DeanWard, I was having the same issue. Then I realized that this package only supports RSA keys. If you're trying with a DSA key it won't work as far as I can tell. Try setting up your ssh with a known working RSA key and then test this package with it.

**Comment by timgavin** [comment]
@DeanWard, @jhoff I'm having the same issue, but when trying to connect with a username and password. How do you connect with the an RSA key? I tried linking to my `~/.ssh/id_rsa.pub` to no avail.

**Comment by gpopoteur** [comment]
I'm having this issue as well, and I'm using a RSA key :-/

**Comment by timgavin** [comment]
I was having this issue and realized I wasn't pointing to the proper key location in my `config/remote.php file`

Once I set it to the right location it worked.

```
'connections' => [
	'MY_SERVER_NAME' => [
		'host'      => 'MY_SERVER_IP',
		'username'  => 'forge',
		'password'  => '',
		'key'       => '/home/forge/.ssh/id_yourkey',
		'keytext'   => '',
		'keyphrase' => '',
		'agent'     => '',
		'timeout'   => 10,
	],
],
```

**Comment by gpopoteur** [comment]
Thanks for the reply @timgavin , I solved it that way as well, figured it out 5 mins ago, I was pointing to the public key, and I should have been pointing to the private key.
