### ISSUE TITLE
L5.4

### ISSUE THREAD

**Issue by NiclasHedam** [LaravelCollective/remote#36]
Support for Laravel 5.4

**Comment by tshafer** [comment]
Ill work on this in the coming week.

**Comment by anuragrath** [comment]
@tshafer Did you get to fix this?
Now as well when I add this it gives error.

Your requirements could not be resolved to an installable set of packages.

**Comment by Fossil01** [comment]
Any updates on this? v5.4.0 throws this error when installing via Composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravelcollective/remote ^5.4.0 -> satisfiable by laravelcollective/remote[v5.4.0].
    - Conclusion: remove phpseclib/phpseclib 0.3.10
    - Conclusion: don't install phpseclib/phpseclib 0.3.10
    - laravelcollective/remote v5.4.0 requires phpseclib/phpseclib ^2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - Can only install one of: phpseclib/phpseclib[2.0.0, 0.3.10].
    - Can only install one of: phpseclib/phpseclib[2.0.1, 0.3.10].
    - Can only install one of: phpseclib/phpseclib[2.0.2, 0.3.10].
    - Can only install one of: phpseclib/phpseclib[2.0.3, 0.3.10].
    - Can only install one of: phpseclib/phpseclib[2.0.4, 0.3.10].
    - Installation request for phpseclib/phpseclib (locked at 0.3.10) -> satisfiable by phpseclib/phpseclib[0.3.10].


Installation failed, reverting ./composer.json to its original content.
```

Looks like it's incompatible with tymondesigns/jwt-auth latest stable version.

**Comment by NiclasHedam** [comment]
As far as I'm concerned, you should be able to update Remote to L54

**Comment by Fossil01** [comment]
I'm installing from scratch and it gives me that error. I guess I should ask over at https://github.com/tymondesigns/jwt-auth

**Comment by mlantz** [comment]
The root of the issue was this package which JWT uses `namshi/jose` but it appears that their latest release supports the phpseclib ^2.0 https://github.com/namshi/jose/blob/7.2.3/composer.json
