### ISSUE TITLE
Can't import class in controller

### ISSUE THREAD

**Issue by GregKeaney** [LaravelCollective/remote#39]
Hey all,  I feel like this is a silly issue (never seen it before) but I have just installed this package.  All good except I can't import the class into my controller.

Trying - use Collective\Remote\RemoteServiceProvider;

But getting - Class 'App\Http\Controllers\SSH' not found

??

**Comment by tshafer** [comment]
Make sure you include and import the Facade.

```      'SSH' => Collective\Remote\RemoteFacade::class,```

**Comment by GregKeaney** [comment]
Hey tshafer,

Did that.

Just found this - http://stackoverflow.com/questions/34357796/laravel-use-ssh-in-controller

Tried use SSH; in controller and that error stopped.  Now getting - Remote connection not defined.

Progress...
Thanks!

**Comment by tshafer** [comment]
Did you set up the configuration file?

https://laravelcollective.com/docs/5.3/ssh#configuration

**Comment by GregKeaney** [comment]
Yep.  It was a typo all caps vs lower case for connection name.

Now getting 'ErrorException in SFTP.php line 1878: test.txt is not a valid file'.  

Trying this;        
        $fileFrom = 'test.txt';
        $fileTo = 'inbound/test.txt';
        SSH::into('sci')->put($fileFrom, $fileTo);

Where test.txt is in app/public/.  Does the package assume public is base dir?

**Comment by tshafer** [comment]
I do not believe so, you should use the absolute path of the file or use a laravel helper.

https://laravel.com/docs/5.4/helpers#method-public-path

**Comment by GregKeaney** [comment]
Interesting.  When I use the absolute path, I still get the not a valid file error.  Odd, not an error that it can't found but that it's not valid...

**Comment by GregKeaney** [comment]
$fileFrom = public_path('test.txt');
$fileTo = 'inbound/test.txt';
SSH::into('sci')->put($fileFrom, $fileTo);

Also returning 'not a valid file' error.  Nothing in the docs to shed any light...

**Comment by GregKeaney** [comment]
Does anyone have a working example of SFTP file upload?

**Comment by mlantz** [comment]
Using the above code worked fine in a fresh install of Laravel 5.4
