### ISSUE TITLE
sftp upload problem 'This service allows sftp connections only.'

### ISSUE THREAD

**Issue by sas05** [LaravelCollective/remote#40]
Hi, while I'm using `SSH::into`, I'm receiving an error "This service allows sFTP connections only."

the server has sFTP enable, while I have tried with file transfer client it has the connection.

**Comment by mlantz** [comment]
SSH is separate from sFTP

https://askubuntu.com/questions/402302/how-can-i-allow-access-to-both-ssh-and-sftp

This may be related to your issue it has a similar response from the server.
