### ISSUE TITLE
Implement filelist function using nlist()

### ISSUE THREAD

**Issue by niraj-shah** [LaravelCollective/remote#42]
Unfortunately, this SSH library doesn't have the ability to request a list of files from a remote server. 

I've tried to run a `ls` commend, but this doesn't work on all connections (e.g. `This service allows sftp connections only.`)

```
SSH::run( 'ls -la', function( $line ) {
    dump( $line );
} );
```

As a work-around, I'm currently using:

```
SSH::getGateway()->getConnection()->nlist();
```

Would be useful to have this included in the Facade.

**Comment by mlantz** [comment]
I cannot replicate this issue. In my test server the `ls -la` works fine.

**Comment by niraj-shah** [comment]
I have the following code, which is attempting to access a SFTP (no SSH commands allowed).

```
SSH::into($this->env)->run( 'ls -la', function( $line ) {
    dump( $line );
} );

$list = SSH::into($this->env)->getGateway()->getConnection()->nlist('.');

dd( $list );
```

This code produces the following output (using `php artisan`):

![Artisan Output](https://www.webniraj.com/wp-content/uploads/2017/05/SSH_Artisan_Output.png)

The issue is that the `run()` function doesn't correctly work on SFTP-only connections. While the `ls -la` command works on the SFTP server directly (i.e. manually logging into SFTP server and running the command), using `SSH::run( 'ls -la' )` via code produces the error `This service allows sftp connections only.`.
