### ISSUE TITLE
Unable to connect to remote server - Laravel 4.1

### ISSUE THREAD

**Issue by qannoufoualid** [LaravelCollective/remote#50]
I want to execute some commands in a remote server using SSH. This is my configuration :

```
'connections' => [
	'production' => [
	    'host'      => '172.55.81.20',
	    'username'  => 'user',
	    'password'  => '',
	    'key'       => 'C:\cygwin64\home\oqannouf\.ssh\id_rsa'
	]
]
```

I tried this : 
`SSH::into('production')->run(['ls']);`
but i get the following error: 
`Unable to connect to remote server` with no additional informations explaining why it doesn't work.
Note:

- The RSA key is correct and i can use it to login to the server using cygwin.

- Even with a correct password it doesn't work.

- I have all the permissions on the folder C:\cygwin64\home\oqannouf.ssh\

**Comment by stidges** [comment]
Are you still experiencing this issue?

**Comment by qannoufoualid** [comment]
After reading and debugging the code of the API (Yeah I know I suffered a lot).
This API unfortunately requires FTP server to be running in the target server :\ which make no sens.
So i got rid of that API and used the Pure-PHP implementation of SSHv2.
This is a class I created that maybe it can help you:

> <?php namespace App\Services;

use SSH;

class SSHService {

    public function execute(array $serverData, array $commands){
        
        $host = $serverData['host'];
        $port = $serverData['port'];
        $userName = $serverData['userName'];
        $password = $serverData['password'];
        
        
        $ssh = new \Net_SSH2($host);
        if (!$ssh->login($userName, $password)) {
            throw new \Exception('Unable to connect to server');
        }
        
        $output = '';
        
        foreach ($commands as $command){
            $output.= $ssh->exec($command);
        }
        
        return trim($output);
    }

}

**Comment by stidges** [comment]
Yeah I'm not sure why a new SFTP instance is always created. Maybe we should implement some sort of driver configuration where a user is able to set driver to 'sftp' or 'ssh' and separate the two gateways

**Comment by qannoufoualid** [comment]
Yes, that's gonna be better. because the is no need to use FTP if you want to use only SSH requests.
