### ISSUE TITLE
SSH with laravel forge provision command

### ISSUE THREAD

**Issue by Te7a-Houdini** [LaravelCollective/remote#51]
i was using laravel forge api to create server 

[https://forge.laravel.com/api-documentation#create-server](url)

and when i execute these two lines of code 

`SSH::run($provisionCommand);`

`SSH::run('bash forge.sh');`

the provision on the server are made but not completed , like the composer isn't installed and root access to the forge server is still allowed . 

but when i run the same provision command from terminal , it works perfectly .

so is there something am missing !?

**Comment by stidges** [comment]
Have you tried saving a reference to the remote? By calling the SSH facade like that twice two separate connections will be created. This might be causing the issue. E.g.:

```php
$ssh = SSH::connection();
$ssh->run($provisionCommand);
$ssh->run('bash forge.sh');
```

**Comment by Te7a-Houdini** [comment]
@stidges thank you for your suggestion , but the problem wasn't that it was a semicolon in the provision command that needs to be added to the response from forge api , i will close the issue
