### ISSUE TITLE
IPV6 support

### ISSUE THREAD

**Issue by Cannonb4ll** [LaravelCollective/remote#60]
Could you add IPV6 support? According to the docs its a matter of changing the fsockopen protocol:

```
Note: When specifying a numerical IPv6 address (e.g. fe80::1), you must enclose the IP in square brackets—for example, tcp://[fe80::1]:80.
```

See: http://php.net/manual/en/function.fsockopen.php

**Comment by tshafer** [comment]
I don't see this happening anytime soon, but we do accept pull requests.
