### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by oytunistrator** [LaravelCollective/remote#66]
`Cannot connect to :22. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known`

**Comment by tshafer** [comment]
Whats this? An error? We are going to need more detail than than. Check the I.P address. According to the error it doesn't exist.

**Comment by oytunistrator** [comment]
This is PHP error. Cant check my local ip address. And 22 port open.

**Comment by tshafer** [comment]
This is a development setup error. Nothing to do with the package.
